# Generated by Django 5.1 on 2024-08-15 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Travail"),
                    ("Personal", "Personnel"),
                    ("Leisure", "Loisirs"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[("E", "Facile"), ("M", "Moyen"), ("H", "Difficile")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
